fileVersion: 1
id: "2"
mappingDefinitions:
  SAMPLE:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
  WORK:
    database: QA_DEPLOY_PHASES2
    schema: QA_DEPLOY_PHASE_2
name: New Environment
type: Environment
